### ISSUE TITLE
JSON control may not work as expected

### ISSUE THREAD

**Issue by aligoren** [mantis-software-company/change-event-service#1]
According to the below lines, the user can define a string like that;

```json
'{ A_KEY: "A_VALUE"'
```

In this case, an exception will be thrown. Do we need try-catch blocks?

```py
def environment_type_converter(s):
    if s == 'True' or s == 'False':
        return strtobool(s)
    elif s.isnumeric():
        return int(s)
    elif s[0] == "[" or s[0] == "{":
        try:
        	return json.loads(s)
        except:
        	pass
    else:
        return s
```

https://github.com/mantis-software-company/change-event-service/blob/3640c00688d91a8d12d48c79de0c903b684873f0/src/change_event_service/utils/settings.py#L13-L14

**Comment by geekdinazor** [comment]
I think bare exceptions are more useful than  managed one. Especially, newer Python versions show the exact location and cause of error.  Passing the exception is generally considered to be an antipattern, in which case the user would like to know if the data we receive from the user is incorrect.
